---

- name: restart neo4j
  ansible.builtin.service:
    name: neo4j
    state: restarted
  become: yes

- name: wait for it to be responsive
  uri:
    url: "localhost:7474/dbms/cluster/status"
    method: GET
    status: 200
    body_format: json
  register: _result
  until: _result.json[0].healthy == true
  retries: 300
  delay: 5
