---
# DEV vars
ENVIRONMENT_TAG: dev
RESOURCE_GROUP: dev_rg
LOCATION: northeurope
CLUSTER_VNET_NAME: dev_vnet
CLUSTER_SUBNET_NAME: dev_subnet
BACKEND_SUBNET_NAME: dev_backend_subnet
CLUSTER_DNS_NAME: cluster.dev
KEY_DATA: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDTKkVpmVvkhWGjbYq1+WbleJRtd0Pm2Hg0axu+N2ViGZht354JGY+MywzZYcO5N8H/s0aP5M+sAf40AyZqoeD/QPs2AHsoA9ZCxCdDl+QAKSdviywE/9SOvBU2SK9h6kj1a7zgEVSmsIlQ29n6A/iDacyWO5qk+LPbhPS/uOl5o0qcj/Avf0QeFBVVdKMRMoQKrgOUR+lMa0q2o9yOAE3G0mOmChvHffapY8fL+fgP4F8OC0Hfnz1fEEuvVDon306RHIsSJP2vZHoXIHyHhSlYybwM0eHllAnJBGicSsti0GlxJdutJ9rmlAKXNqYW147CKWR8Wax9Ym1DCPc9dC5ZMEiWl5DJQqZoJ3YuwQ4v8X0lkb6ixt1q/mdo2D1rNxCGMxTqMibHBrMlGOHg/J1zLtGtamavFS8XR7nrjZk8qbqdqSZIf0ppMeWIKrhXtkV5v0qg6Zn+eveQhAiciVyQYvhEJM/mkEGABP8+svN9wAGJG7mweXfNH10Yvb3RWicgETwtEHrt3FNLRbO+1MCFvZ9PL1E8YDE85kRqnDOtYnz/rg4beF2b+/4NJuVSI2IOoC8FEQkqXytyMe+JE0WtNtndfSgKT0pjE7wv1VDs1Ll/RT5aaPEMW6jFjH7u9hD39ONPFcZuFR1cHrsYMBpHEjPGNaptf8qYu09HIy9YoQ== hakan.lofqvist@neo4j.com"
